### ISSUE TITLE
[Bug] SDK YAML tests fail at the commissioning step

### ISSUE THREAD

**Issue by uritustefan** [project-chip/certification-tool#178]
### Describe the bug

When running any SDK YAML test using the TH, the harness returns an error stating the commissioning failed and "Buffer too small" can be seen in the logs. On the DUT side, the logs indicate that the commissioning was successful.

Using the same command found in the log provided by the TH, the commissioning works fine manually.
I tried re-flashing the TH image on the RPI and the problem is still seen.

### Log files

[UI_Test_Run_2024_02_08_16_25_00.log](https://github.com/project-chip/certification-tool/files/14220723/UI_Test_Run_2024_02_08_16_25_00.log)

### Environment

Version: 2.10-beta2.2+spring2024Sha: 2432a29

**Comment by antonio-amjr** [comment]
Hi @uritustefan

Can you please share three things for the investigation:
- The DUT's log from the TH run
- The project's configuration
- The "Test Harness Doctor" output (run the `./scripts/th/th-doctor.sh` repo script)

Thanks!

**Comment by uritustefan** [comment]
[th_doctor_output.txt](https://github.com/project-chip/certification-tool/files/14308546/th_doctor_output.txt)
[project_configuration.txt](https://github.com/project-chip/certification-tool/files/14308548/project_configuration.txt)
[DUT_log.txt](https://github.com/project-chip/certification-tool/files/14308549/DUT_log.txt)

Hello. I've uploaded the files you requested

**Comment by antonio-amjr** [comment]
Hello again @uritustefan,

First, thanks for sharing the files.
Sorry about the delay.
About the "Buffer too small" error that appears in the log, there's another issue focused on that in the following link: https://github.com/project-chip/certification-tool/issues/153

Let's see if their investigations help your problem.

----------------------
Meanwhile, let me ask for your help here, since I don't have the test environment set:

One thing odd to me is that the buffer error doesn't stop the pairing process.
The last step is actually the "ThreadNetworkSetup". Made me wonder...

I saw that the project's config is the default, beside the `test_parameters`.
I'm assuming you're **NOT** using the `scripts/OTBR/otbr_start.sh` and TH automatically brings up the OTBR, right?
 
Can you try **one** of these two options:
1. Remove `thread-dataset-hex` completely from `test_parameters` (to verify if SDK YAML already has this info)
2. Use `thread-dataset-hex` = `000300000f02081111111122222222051000112233445566778899aabbccddeeff01021234` (to verify if that's the simple dataset expected from your config)

**Comment by uritustefan** [comment]
Hello. I've closed the issue as it is no longer reproducing with the latest TH from the latest SVE. We couldn't pinpoint exactly what the cause was.
