### ISSUE TITLE
[TC-IDM-10-2] Failed in unexpected situation 

### ISSUE THREAD

**Issue by VaishaliAvhale** [project-chip/certification-tool#380]
### Describe the bug

I'm using a DUT that supports the WiFi feature, so I selected the WiFi feature in the PICS file. However, I'm facing a strange issue: 'Problem: Required feature with mask 0x01 is not present in the feature map. Conformance: WI, implemented features: WI.
Please find attached logs and PICS file

### Steps to reproduce the behavior

1. Commission Wifi supported DUT and execute TC_10_2

### Expected behavior

It should pass because  correct PICS element is selected. 

### Log files

[TC_IDM_10_2_esp32c3.log](https://github.com/user-attachments/files/16637124/TC_IDM_10_2_esp32c3.log)
[TC_IDM_10_2_TH_2024_08_16_10_36_11 (1).log](https://github.com/user-attachments/files/16637126/TC_IDM_10_2_TH_2024_08_16_10_36_11.1.log)

### PICS file

[Network Commissioning Cluster Test Plan.zip](https://github.com/user-attachments/files/16637137/Network.Commissioning.Cluster.Test.Plan.zip)

### Screenshots

![image](https://github.com/user-attachments/assets/3af7f66e-7158-4e22-a5c2-3390eb173775)

### Environment

TH Version:  v2.11-beta2+fall2024

### Additional Information

 have read the feature map of the firmware that I used and attached the logs in the log file. You can check this for confirmation.

**Comment by rquidute** [comment]
Hi @cecille could you please take a look at this?

**Comment by cecille** [comment]
This isn't PICS related, it's happening because the data model "source of truth" contains features that are not slated for inclusion in 1.4, but none the less appear in the scrape because I didn't have a definitive list before the test event started, so we're going off spec master.

But also, the error message has a typo, which doesn't help the situation.

Typo in the error message fixed here: https://github.com/project-chip/connectedhomeip/pull/35044

The data model XML scrape is something that's on the docket to address before SVE. The hope is that we'll have a better handle on what's in and what's out by SVE timeframe. Sorry about that - the feature list was heavily in flux, so we did what we could. For reference - it's the PDC feature from hrap that it's actually complaining about. See https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/NetworkCommissioningCluster.adoc?plain=1#L140

**Comment by fabiowmm** [comment]
Seems originator has lost interest. Please reopen if you are still facing the problem.
