### ISSUE TITLE
[Bug] Not able to perform decommissioning in simulated test case 

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#40]
From chip-certification-tool created by [Ashwinigrl](https://github.com/Ashwinigrl): CHIP-Specifications/chip-certification-tool#950  

### Describe the bug

Last step of all simulated test case there is a step prompting to decommission the DUT, But when trying to decommission using chip-tool command it end with timeout. Timeout during decommission happens only if it is already decommissioned. 

I believe that runner is automatically decommissioning the DUT and prompting for decommissioning if in that case the prompt has to be removed if not the runner needs attention for the same.  

### Steps to reproduce the behavior

1. Open the UI
2. Upload the PICS
3. Ensure the Simulated test case is selected
4. Click on start
5. UI Prompts for commissioning
6. Provide the pairing code in DUT with payload
7.  Provide the command as per the prompts
8. After completion of test case execution, Provide the Unpairing code in DUT with payload

### Expected behavior

DUT should Decommissioned successfully 

### Log files

**Ex log for TCOCC-2.4:**
[Simulated backend log.txt](https://github.com/CHIP-Specifications/chip-certification-tool/files/12465077/Simulated.backend.log.txt)
[TC-OCC-2.4(DUT).txt](https://github.com/CHIP-Specifications/chip-certification-tool/files/12465078/TC-OCC-2.4.DUT.txt)

### Environment

TH Version: TH Fall2023
Sha: 58a51bef

### Additional Information

**Facing this issue for all the simulated test cases**

**Comment by ccruzagralopes** [comment]
This is happening because the `./chip-app1` instance that runs in the SDK container during the tests stops running once the testing is completed. TH used to launch it again at the test suite cleanup in order to perform this decommissioning step, but that has been removed when the runner was integrated. So now the DUT will try to decommission but `./chip-app1` will not be running, hence the timeout.

We can come back to doing it like before for now and then think of a better solution for this, since the code has a comment saying "Need a better way to trigger unpair for chip-app."

**Comment by ccruzagralopes** [comment]
Fixed in https://github.com/project-chip/certification-tool-backend/pull/29. This fix is in the backend repository. This should be included in the next TH release.

**Comment by Ashwinigrl** [comment]
Fixed this Issue in latest TH **Version**: main - dev **Sha**: f17efc4.
Hence closing this issue
