### ISSUE TITLE
[Bug] Testharness 1.4 selects too many not needed tests

### ISSUE THREAD

**Issue by LarsOesten** [project-chip/certification-tool#437]
### Describe the bug

The test plan generator in the Testharness selects far to many tests. Most of these tests are even not applicable to the selected xml file. The online pics tool prints out the correct tests according to the selected xml file

### Steps to reproduce the behavior

1. Select a single xml file, e.g. "Access Control Cluster Test Plan.xml", and create a new project in the testharness
2. approximately 75 tests are selected

### Expected behavior

The online pics tools selects 11 TC-ACL tests, if "Access Control Cluster Test Plan.xml" is used. The testharness should have the same amount of tests.

### PICS file

default "Access Control Cluster Test Plan.xml" for Matter 1.4. All pics are set to be supported.

**Comment by fabiowmm** [comment]
Regarding the issues faced with the TH Certification Mode, our recommendation is for users to initially run test cycles against their DUTS in certification mode and then afterwards repeat the failing ones in the regular (non-certification) mode. The test logs from the regular mode are no different from the ones generated by certification mode and can also be used for certification.
Certification mode is an experiment on providing some DUT-driven test case selection in which **all test scripts** are launched by TH and **each script itself figures out whether it should run or not**. We learned from the SVE that, due to the current latency when running multiple python tests from the UI, this is not yet very practical.
