### ISSUE TITLE
[Bug] Test steps are not being shows for all python tests

### ISSUE THREAD

**Issue by cecille** [project-chip/certification-tool#457]
### Describe the bug

There are a bunch of tests where we have steps_ functions defined, but the individual steps are not displayed in the GUI

### Steps to reproduce the behavior

This happens for opstate tests for example, but I assume also others.

**Comment by fabiowmm** [comment]
@antonio-amjr can you try to reproduce this with `TC_OPSTATE_2_1.py`?

**Comment by antonio-amjr** [comment]
> @antonio-amjr can you try to reproduce this with `TC_OPSTATE_2_1.py`?

Sure, I'll take a look

**Comment by antonio-amjr** [comment]
@cecille and @fabiowmm ,

The OPSTATE and OVENOPSTATE tests are falling into the **legacy** python test category.
That is happening because the _Python Test Parser_ is expecting a `ast.List` type from the "steps_" method, but instead is receiving a `ast.Call`. 

So the problem is that the OPSTATE/OVENOPSTATE tests are the only ones, I believe, that are using another method to retrieve the steps, like shown below:
<p align="center">
<img width="569" alt="Screenshot 2024-10-11 at 09 15 25" src="https://github.com/user-attachments/assets/5e918bbf-37d7-49a6-b4ea-57e025446f75">
<br><b>The python_test_parser.py method verifying the test steps type.</b>
</p>

<p align="center">
<img width="549" alt="Screenshot 2024-10-11 at 09 11 58" src="https://github.com/user-attachments/assets/03b41eb6-9665-4886-a478-b4e2c041d874">
<br><b>The original TC_OPSTATE_2_1 steps method that triggers the error.</b>
</p>

<p align="center">
<img width="686" alt="Screenshot 2024-10-11 at 09 22 48" src="https://github.com/user-attachments/assets/de3bded2-9875-4baa-bab9-7058130306f4">
<br><b>Changing the TC_OPSTATE_2_1 steps method successfully adds to the correct suite and show the steps in execution.</b>
</p>

---
I think that the steps are specific to tests and shouldn't be inside the `TC_OpstateCommon.py` at all. And to solve this would be just moving the steps to each related file.

What is your take on this?

**Comment by antonio-amjr** [comment]
> [!NOTE]  
> It seems that there's a feature already in progress that solves this issue:
> - https://github.com/project-chip/certification-tool-backend/pull/106

**Comment by rquidute** [comment]
Related issue: https://github.com/project-chip/certification-tool/issues/484

**Comment by fabiowmm** [comment]
@rquidute is this solved?
