### ISSUE TITLE
[Bug] TC-TIMESYNC-2.3 fails if TIMESYNC.S.F03 is not supported

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#47]
From chip-certification-tool created by [pankore](https://github.com/pankore): CHIP-Specifications/chip-certification-tool#967  

### Describe the bug

If declared not supporting TIMESYNC.S.F03 and disable TrustedTimeSource (TIMESYNC.S.A0003), the automated script will fail.
PICS is not indicated in the test plan, and automated script does not include PICS.

Step requiring PICS 1, 3, 4, 5

Test-plan:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/time_synchronization.adoc#tc-timesync-2-3-settrustedtimesource-command-with-dut_server

### Log files

Test Harness log:
[TC-TIMESYNC-2.3.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/12583256/TC-TIMESYNC-2.3.log)

**Comment by raju-apple** [comment]
@rquidute TC-TIMESYNC-2.3 test uses `TIMESYNC.S.F03` high level pics and it should not be executed when TIMESYNC.S.F03 is `false`.
@pankore Seems like a test-plan issue please file a ticket in test-plan repo, once test-plan is updated we will update the script accordingly.

**Comment by raju-apple** [comment]
@manjunath-grl I had filed an issue but doesn't seem to have assign to anyone. https://github.com/CHIP-Specifications/chip-test-plans/issues/3433

**Comment by raju-apple** [comment]
@pankore  AND @rquidute 

The TC-TIMESYNC-2.3 test case is depending  on TIMESYNC.S.F03 at a high level in the PICS, and the test case will not be selected if TIMESYNC.S.F03 is set to false.

![Screenshot from 2023-09-15 15-16-30](https://github.com/CHIP-Specifications/chip-certification-tool/assets/95841834/aecd699e-f064-4fdb-bd05-ab54183254e9)

And it's not a Test-plan Issue 
PICS for all time sync test cases apply to the entire test and are listed in the PICS section at the top of the test. None of the tests have individual steps that are PICS-gated

Issue raised for the same earlier : https://github.com/CHIP-Specifications/chip-test-plans/issues/3219

**Comment by rquidute** [comment]
There is a note in Issue https://github.com/CHIP-Specifications/chip-test-plans/issues/3433 asking to test again since this PR was merged: https://github.com/project-chip/connectedhomeip/pull/29378

I performed an execution in my setup and the test passed.
![Screenshot 2024-01-15 at 14 30 37](https://github.com/project-chip/certification-tool/assets/116586593/38e72bc7-d06e-4d76-8014-adf5a2695494)

**Comment by rquidute** [comment]
Hi @manjunath-grl is this issue still valid? I was able to run successfully.

**Comment by manjunath-grl** [comment]
The test script aligns with the test plan, and no modifications are needed since the comment in issue [3433](https://github.com/CHIP-Specifications/chip-test-plans/issues/3433#issuecomment-1749441234) suggests that the SDK has been fixed. The ticket owner should retest this test case.
CC @raju-apple @rquidute
