### ISSUE TITLE
[Bug] YAML cannot be applied successfully

### ISSUE THREAD

**Issue by ifdreams** [project-chip/certification-tool#89]
### Describe the bug

![image](https://github.com/project-chip/certification-tool/assets/18089130/31169dff-49da-4cab-b6ec-51bf260e2b63)
![image](https://github.com/project-chip/certification-tool/assets/18089130/ce017263-fd84-4f0e-8ac5-a2f8f1007806)
![image](https://github.com/project-chip/certification-tool/assets/18089130/07b94403-ee9e-4e77-9690-a1b9b9bdecf4)

### Steps to reproduce the behavior

1，Matter_TH_User_Guide.adoc  ---> 4.5  Updating Existing Yaml Test Script
2,   chip-certification-tool/backend/test_collections/yaml_tests/yaml/sdk/Test_TC_LVL_3_1.yaml 

--   - label: "Step 5f: TH sends Off command to DUT"
++  - label: "Step 5f: TH sends Off command to DUT.rex"
      cluster: "On/Off"
      PICS: OO.S.C00.Rsp
++ #add by rex
 --  command: "Off"
++ command: "On"

3.$docker restart chip-certification-tool_backend_1

### Expected behavior

Test Step Not Applicable: Step 5f: TH sends Off command to DUT.rex 
Test Step Completed [PASSED]: Step 5f: TH sends Off command to DUT.rex

**Comment by hiltonlima** [comment]
Good morning @ifdreams,

From what we analyzed here, your changes made to YAML were applied. We can confirm in the log (image) you posted.

Now if the idea you had was to make the test step run... You need to change the value of [PICS: LVL.S.COO. Rsp] PICS file.


Please, if the reason is different... could you please describe it?
